### ISSUE TITLE
Saisie du contenu

### ISSUE THREAD

**Issue by MbayoG** [dil-classroom/projet-bijelic_coke_mbayo_salhi#24]
# User story
## Description 

En tant qu’utilisateur, 
j’aimerais pouvoir saisir du contenu dans un format de markup simplifié tel que Markdown
ou Asciidoctor qui sera compilé en HTML

### Sous-stories
- [x] Markdown

### Optimiste

| **Nombre d'heures** | 1 |
|-----------------------------|---|

### Pessimiste 

| **Nombre d'heures** | 3 |
|-----------------------------|---|

### Attendu 

| **Nombre d'heures** | 2 |
|-----------------------------|---|

### Temps pris en pratique

| **Nombre d'heures** | 1 |
|-----------------------------|---|

# Liens utiles
- [CommonMark](https://github.com/commonmark/commonmark-java)
- [FlexMark](https://github.com/vsch/flexmark-java)
- [Pandoc](https://www.youtube.com/watch?v=sZBmoiFTJVY)

**Comment by b0ogieMan** [comment]
@MbayoG "Temps pris en pratique" has been updated !
