### ISSUE TITLE
Affichage de la version

### ISSUE THREAD

**Issue by MbayoG** [dil-classroom/projet-bijelic_coke_mbayo_salhi#26]
# User story
## Description 

En tant qu’utilisateur, j’aimerais exécuter la commande suivante de manière à afficher la version du générateur de
site statique dans le terminal.

Exemple:
$ statique –version

### Sous-stories
- [ ] Implémenter des tests unitaires
- [ ] Implémenter la commande

### Optimiste

| **Nombre d'heures** | 1 |
|-----------------------------|---|

### Pessimiste 

| **Nombre d'heures** | 2 |
|-----------------------------|---|

### Attendu 

| **Nombre d'heures** | 1.5 |
|-----------------------------|---|

### Temps pris en pratique

| **Nombre d'heures** | - |
|-----------------------------|---|

# Liens utiles
- [Option d'affichage de version générée automatiquement par *picocli*](https://picocli.info/#_mixin_standard_help_options)

**Comment by b0ogieMan** [comment]
À l'air de déjà fonctionner dans notre version actuelle. En effet, en testant de lancer l'application avec `static --version` le message suivant s'affiche dans la console : 
```static 0.1```

Selon la [documentation](https://picocli.info/#_mixin_standard_help_options), la ligne `mixinStandardHelpOptions = true` ajoutée par @AlenBijelic99 permet déjà d'avoir l'option *--version / -V*
