### ISSUE TITLE
Initialiser un site statique

### ISSUE THREAD

**Issue by MbayoG** [dil-classroom/projet-bijelic_coke_mbayo_salhi#27]
# User story
## Description 
En tant qu’utilisateur, j’aimerais exécuter la commande suivante de manière à initialiser un site statique dans le
dossier /mon/site.

$ statique init /mon/site

En d’autres termes, la sous-commande init pourrait créer ou enrichir le dossier nommé /mon/site avec un fichier
de configuration config.yaml contenant des informations générales liées au site (titre, description, domaine, etc.) et
un fichier Markdown index.md contenant une page d’accueil avec des métadonnées et du contenu.

### Sous-stories
- [x] Tests unitaires
- [x] Création config.yaml
- [x] Création index.md
- [x] Remplir config.yaml
- [x] Remplir index.md

### Optimiste

| **Nombre d'heures** | 2 |
|-----------------------------|---|

### Pessimiste 

| **Nombre d'heures** | 4 |
|-----------------------------|---|

### Attendu 

| **Nombre d'heures** | 3 |
|-----------------------------|---|

### Temps pris en pratique

| **Nombre d'heures** | 3 |
|-----------------------------|---|

# Liens utiles
- [Paramètres positionnels avec *picocli*](https://picocli.info/#_positional_parameters)

**Comment by MehSalhi** [comment]
Done:
- directory strucuture
- File creation
- unit test

ToDo:
- fill the file either by writing the content or copying a file template. Copy should be a better option. Waiting on #36 for temnplates.
